spring.application.name=via_cep

spring.datasource.url=jdbc=mysql://localhost:3306/desenvolvimento_sistemas
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver