# ============================================
# 🔹 Configuração básica do aplicativo
# ============================================
spring.application.name=backend
server.port=8080
server.forward-headers-strategy=framework

# ============================================
# 🔹 Banco de Dados MySQL
# ============================================
spring.datasource.url=jdbc:mysql://localhost:3306/desenvolvimento_sistemas?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=$Crud1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ============================================
# 🔹 JPA / Hibernate
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ============================================
# 🔹 Login com Google (OAuth2)
# ============================================
spring.security.oauth2.client.registration.google.client-id=288953626303-04pjr9gettsejqma64qm95rmvia959jv.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.client-name=Google
# client-name, name-attribute, scope, são acrescentados
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# ============================================
# 🔹 Configuração de E-mail (Gmail SMTP)
# ============================================
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=fatecmeets@gmail.com
spring.mail.password=eximrybnuktaofwh

# Autenticação e segurança
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=true

# Informações do remetente padrão
mail.from.address=fatecmeets@gmail.com
mail.from.name=Fatec Meets

github.token=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
